# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja"

reviews:
  high_level_summary: true
  high_level_summary_instructions: "Short bullets. Mention risks and test gaps."
  auto_review:
    enabled: true
